### ISSUE TITLE
Issue with auto rename feature from AvatarMenuCreatorForMA

### ISSUE THREAD

**Issue by Spokeek** [Narazaka/AvatarParametersExclusiveGroup#1]
Hi, i was using the exclusive group feature with the MenuCreator and i believe i found an issue with the AutoRename Feature.

As we setup the values from within the component for AvatarParametersExclusiveGroup in text, if we enabled the "AutoRename" feature from the MenuCreator, we provoke an error at build time.

I don't know if that needs to be fixed or if a warn needs to be added, but felt that needed to be reported.

![image](https://github.com/Narazaka/AvatarParametersExclusiveGroup/assets/4519853/f8e7ffa9-9618-4d36-b922-a31fe254138e)

**Comment by Narazaka** [comment]
Auto rename in AvatarMenuCreator is in accordance with the Modular Avatar specification and must be used within its constraints.
Specifically, the name is only valid under the Avatar Toggle Menu Creator component and other components.

**Comment by Spokeek** [comment]
Fair, but i believe it's confusing as the selector in the Component suggests the use of that parameter. Maybe we shouldn't add the parameters that have that feature, or warn the user about it. If you think it's out of scope, tell me so and you can't close the issue.

**Comment by Narazaka** [comment]
Fixed a dependency library so that the auto-rename parameter is not displayed.
Install Avatar Parameters Util (net.narazaka.vrchat.avatar-parameters-util) 2.0.3.
